# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Open Source Days"
email: "devfest@gdg.org.ua"
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "https://dwo.info.pl"
permalink: "/blog/:title"
languages: ["pl", "en"]
gems:
  - jekyll/multiple/languages/plugin

# Organizer Info
organizerName: "Hackerspace Silesia"
organizerAlternateName: "Hackerspace Sielsia"
organizerDescription: "Hackerspace Silesia is community of geeks and hackers who are passionate about playing with technology, creating new things and explore new possibilites."
organizerEmail: "info@hs-silesia.pl"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://hs-silesia.pl/"

# Head
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform"


# TRANSLATION with Arrays
pl:
  navigationLinks:
   - {permalink: "/", text: "Home"}
   - {permalink: "/blog/", text: "Blog"}
   - {permalink: "/schedule/", text: "Agenda"}
   - {permalink: "/speakers/", text: "Prelegenci"}
   - {permalink: "/team/", text: "Zespół"}
   - {permalink: "/logistics/", text: "Miejsce"}
  bottomNavigationLinks:
   - {link: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform", text: "Zostań prelegentem"}
  rightNavigationButtons:
   - {link: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform", text: "Zostań prelegentem"}
  aboutTitle: "O Dniach Wolnego Oprogramowania"
  aboutBlock:
  - {title: "Idea", image: "conference.jpg", text: "Ruch Open Source to przede wszystkim nastawienie na innowacyjność, kreatywność i chęć dzielenia się wiedzą. Nie ogranicza się on wyłącznie do kodu źródłowego aplikacji - ruch ten wywiera wpływ na ekologię, sprzęt, powszechny dostęp do wiedzy i edukacji." }
  - {title: "Społeczność", image: "workshop.jpg", text: "Żadna idea nigdy nie odniosła sukcesu bez zaangażowania zwykłych ludzi. Ty również możesz zmieniać świat wokół nas! ‘Uwolnij się’ :-) i dołącz do społeczności Open Source!" }
  - {title: "Warsztaty", image: "hackathon.jpg", text: "W społeczności Open Source jest wiele osób, które posiadają konkretne umiejętności, a przy tym chętnie się nimi dzielą. Wielu jest również tych, którzy starają się tego rodzaju umiejętności w sobie wykształcić. Warsztaty pozwalają im się spotkać." }
  ticketsTitle: "Bilety"
  ticketsOffers:
   -
    name: "Bilet pingwinka na konferencję DWO"
    price: "FREE!"
    ticketsNumber: "400"
    featured: true
    buyButtonLink: ""
    buyButtonText: "Zbierz wejściówkę teraz!"
    ticketContentList: ["Warsztaty", "Prelekcje", "Unconference"]
    validFrom: "2016-05-25T00:00"
    validThrough: "2016-06-12T23:59"
    disabled: true
  # Venue Block
  venueBlockTitle: "Miejsce"
  venueTitle: "Budynek L ATH"
  venueFeatures: ["Sala na 300 osób", "Sale warsztatowe", "Blisko gór"]

  # Hero Block
  heroImage: "hero.jpg"
  eventDate: "10-12 czerwca, 2016"
  typeoutTextValues: '"", "Bielsko-Biała", "Polska", "ATH"'
  typeoutFallback: "Season"
  heroButtons:
   - {link: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform", text: "Zostań prelegentem"}
   - {permalink: "/#tickets", text: "Zdobądź bilet!"}

  footerBlocks:
   -
    title: "Kontakt"
    links:
     - {link: "mailto:kontakt@hs-silesia.pl", text: "kontakt@hs-silesia.pl"}
   -
    title: "FAQ"
    links:
     - {permalink: "/cod/", text: "Kodeks postępowania"}
  # Partners Block
  organizersTitle: "Organizatorzy"
  partnersTitle: "Partnerzy"
  partnersC4sponsorsButton: "Zostań sponsorem"
  statisticBlockImage: "statistic.jpg"
  statisticBlock:
   - {count: "300", specialCharacter: "+", info: "uczestników", detail: "z całej Polski"}
   - {count: "20", specialCharacter: "+", info: "prelegentów", detail: "z różnych dziedzin"}
   - {count: "3", specialCharacter: "", info: "dni", detail: "świata otwartego oprogramowania"}
  blogTitle: "Aktualności"
  latestNewsTitle: "Aktualności"

  directionDetailsTitle: "Informacje o Bielsku-Białej"
  directionDetailsCards:
   - {title: "Transport publiczny", information: 'By poruszać się po bielsku polecamy rozkład jazdy MZK http://www.mzkb-b.internetdsl.pl/linie.htm'}
   - {title: "Hotele", information: 'Bielsko-Biała ma wiele dobrych hosteli i hoteli..'}
   - {title: "Góry", information: 'Z Bielska-Białej można szybko wyskoczyć w góry na Szyndzielnię lub Klimczok.'}
  # Team Block

  teamBlockTitle: "O nas"
  aboutUs: "Jesteśmy pasjonatami!"

en:
  navigationLinks:
   - {permalink: "/", text: "Home"}
   - {permalink: "/blog/", text: "Blog"}
   - {permalink: "/schedule/", text: "Schedule"}
   - {permalink: "/speakers/", text: "Speakers"}
   - {permalink: "/team/", text: "Team"}
   - {permalink: "/logistics/", text: "Logistics"}
  bottomNavigationLinks:
   - {link: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform", text: "Become a speaker"}
  rightNavigationButtons:
   - {link: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform", text: "Become a speaker"}
  aboutTitle: "About Open Source Days"
  aboutBlock:
  - {title: "Idea", image: "conference.jpg", text: "Ruch Open Source to przede wszystkim nastawienie na innowacyjność, kreatywność i chęć dzielenia się wiedzą. Nie ogranicza się on wyłącznie do kodu źródłowego aplikacji - ruch ten wywiera wpływ na ekologię, sprzęt, powszechny dostęp do wiedzy i edukacji." }
  - {title: "Community", image: "workshop.jpg", text: "Żadna idea nigdy nie odniosła sukcesu bez zaangażowania zwykłych ludzi. Ty również możesz zmieniać świat wokół nas! ‘Uwolnij się’ :-) i dołącz do społeczności Open Source!" }
  - {title: "Workshops", image: "hackathon.jpg", text: "W społeczności Open Source jest wiele osób, które posiadają konkretne umiejętności, a przy tym chętnie się nimi dzielą. Wielu jest również tych, którzy starają się tego rodzaju umiejętności w sobie wykształcić. Warsztaty pozwalają im się spotkać." }
  ticketsTitle: "Tickets"
  ticketsOffers:
   -
    name: "Pinguing tickets on OSD conference"
    price: "Conference is free"
    ticketsNumber: "400"
    featured: true
    buyButtonLink: ""
    buyButtonText: "Zbierz wejściówkę teraz!"
    ticketContentList: ["Warsztaty", "Prelekcje", "Unconference"]
    validFrom: "2016-05-25T00:00"
    validThrough: "2016-06-12T23:59"
    disabled: true
  # Venue Block
  venueBlockTitle: "Venue"
  venueTitle: "Building L ATH"
  venueFeatures: ["300 seats", "Workshops", "Near mountains"]

  # Hero Block
  heroImage: "hero.jpg"
  eventDate: "10-12 June, 2016"
  typeoutTextValues: '"", "Bielsko-Biała", "Polska", "ATH"'
  typeoutFallback: "Season"
  heroButtons:
   - {link: "https://docs.google.com/forms/u/0/d/1g1DiBheRSBTqCL5YPWfd1RAqqfPZrITz4J2LDIeUbH4/viewform", text: "Become a speaker"}
   - {permalink: "/#tickets", text: "Get tickets"}
  footerBlocks:
   -
    title: "Contact"
    links:
     - {link: "mailto:kontakt@hs-silesia.pl", text: "kontakt@hs-silesia.pl"}
   -
    title: "FAQ"
    links:
     - {permalink: "/cod/", text: "Code of Conduct"}

  organizersTitle: "Organizers"
  partnersTitle: "Partners"
  partnersC4sponsorsButton: "Become a sponsor"

  # Statistic Block
  statisticBlockImage: "statistic.jpg"
  statisticBlock:
   - {count: "300", specialCharacter: "+", info: "attendees", detail: "from whole Poland and Europe"}
   - {count: "20", specialCharacter: "+", info: "speakers", detail: "with different expertise"}
   - {count: "3", specialCharacter: "", info: "days", detail: "world of open source"}

  blogTitle: "Latest news"

  latestNewsTitle: "Latest news"

  directionDetailsTitle: "Informacje o Bielsku-Białej"
  directionDetailsCards:
   - {title: "Transport publiczny", information: 'By poruszać się po bielsku polecamy rozkład jazdy MZK http://www.mzkb-b.internetdsl.pl/linie.htm'}
   - {title: "Hotele", information: 'Bielsko-Biała ma wiele dobrych hosteli i hoteli..'}
   - {title: "Góry", information: 'Z Bielska-Białej można szybko wyskoczyć w góry na Szyndzielnię lub Klimczok.'}

  # Team Block
  teamBlockTitle: "About us"
  aboutUs: "We are geeks!"



venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Miejsce"
eventLocationName: "ATH "
eventLocationLink: "http://info.ath.bielsko.pl/"
eventStreetAddress: "Willowa 2"
eventAddressLocality: "Bielsko-Biała"
eventAddressLocalityRegion: "Śląsk"
eventPostalCode: "43-300"
eventAddressCountry: "Polska"
eventStartTime: "2016-06-10T15:00"
eventDoorTime: "15:00"
eventStartTime: "2016-06-12T15:00"
eventPlaceCoordinates: "49.783050, 19.057579"
mapCenterCoordinates: "49.7841414, 19.0577026"
mapMobileCenterCoordinates: "49.7841414, 19.0577026"

# Tweets Feed Block
# tweetsFeedImage: "twitter-feed.jpg"
# tweetsFeedTitle: "What's Up?"
# twitterHashTag: "dwo"
# twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://web.facebook.com/Dni-Wolnego-Oprogramowania-158202210939470", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}

# Blog
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: false


# Logistics Find Way Block
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"

# directionDetailsWideCards:
#  -
#   title: "Questions?"
#   subCards:
#    -
#     title: "Hotels"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Registration"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#    -
#     title: "Attendance Details"
#     links:
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#      - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
